### ISSUE TITLE
Add Form Component - Select

### ISSUE THREAD

**Issue by nizniz187** [Padax/w-components#23]

**Comment by yakkowu** [comment]
# TASK COMPLETE!

You can see the first section is called "Select types", it comes in two types:
- Filled Select
- Outlined Select

PS For now, we provide the most basic style of this Select component.

⤷ Here's the currently file [in Figma](https://www.figma.com/file/5mAH9laNFI4q3oJeTN0sgq/Design-System?node-id=1211%3A342).

![image](https://user-images.githubusercontent.com/46119829/145256016-7fc04af4-a30c-4406-b4db-0ecdd4a722ae.png)

**Comment by cwpeng** [comment]
Completed select UI without options. I will continue working on this.

**Comment by cwpeng** [comment]
Implement native options.

1. build w-option component only for attributes passing now, but in the future, it can be important customizable part.
2. use slotchange event to build native options from w-option attributes.
3. use first option as placeholder for select component.

@yakkowu @nizniz187 review requirement.

**Comment by cwpeng** [comment]
Implement value update, but not selectedIndex attribute because customized element cannot use uppercase letter in attribute name defined in standard. Developer can still set value for changing select component, it's enough to do anything.

https://stackoverflow.com/questions/44347580/can-custom-elements-attributes-be-camelcased

**Comment by nizniz187** [comment]
Please look into the following issues:
1. `slotchange` is successfully triggered on DOM manipulations (create/delete `w-option`), but not on DOM attribute changes (update `w-option` attributes).
2. Accessing `w-select.value` always returns empty string.
3. Change selected option got an error:
    ```
    Select.js:93 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
        at HTMLSelectElement.change
    ```

**Comment by cwpeng** [comment]
Done.

**Comment by yakkowu** [comment]
Here's an overview of the features of our Select component, as a reminder of these directions in the future.

Currently Select provides the following basic styles and functions:
- Types
  - Filled Select
  - Outlined Select
- Function
    - Single-option

**In the next stage**, it's expected to update:
- Types
- Function
  - Multi-option (tagging style)
- Assistance
  - Help message
  - Error message
  - Label
  - A complex of all above

**Comment by nizniz187** [comment]
@cwpeng
Please look into the following issues:
1.  `slotchange` is still not triggered for `w-option` inner HTML changes.
2. Setting all options disabled causes an exception (should follow how native `select` acts):
    ![image](https://user-images.githubusercontent.com/6836873/151705063-d7677d2c-4448-4f7a-b42f-37871cb15195.png)
3. If the user programmically set the value to `null` or `undefined`, it should be converted to the default value (empty string) so that the placeholder can be selected automatically.

**Comment by cwpeng** [comment]
1. I prefer to ignore this at this time because we have large chance to change to customized option in the future.
2. Done.
3. Done.

**Comment by nizniz187** [comment]
Looks all good.
Will open a new issue for `w-option` inner HTML changes on the next stage.
